name: me360-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - sympy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - tensorflow
  - astropy
  - poliastro
  - astroquery
  - plotly
